# -*- coding: utf-8 -*-
"""MatploptSeaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZHF9e8EKrAGEO2XI-PJLOvdPb0_NLFEO
"""

import numpy as np
import matplotlib.pyplot as plt
runs=np.array(([100,50,91,78,89,25,34,19,9,10]))
w=(np.array([1,0,2,0,3,7,8,9,7,5]))
plt.plot(w,runs,color='red')
plt.title('IndVsAus_score')
plt.legend(loc='best')
plt.show()

tigar=np.linspace(-2*np.pi,2*np.pi,100)
print(tigar)

plt.plot(tigar,np.sin(tigar),linestyle='dotted',color='black')
plt.title('sin')
plt.show()

overs = np.arange(5,50,5)
overs_a = np.arange(5,30,5)
runs_i = np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wickets = np.array([12,32,96])
plt.plot(overs,runs_i,color='blue',label='India')
plt.plot(overs_a,runs_a,color='yellow',label = 'Aus')
plt.legend(loc='best')
plt.show()

a = [230,560,780,127,128]
b = [200,160,270,127,400]
years = [1,2,3,4]
profit_a = [(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth = '6',label = 'CompanyA',marker='.',ms='20',mec='m')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label = 'CompanyB',marker = 'H')
plt.show()

a = np.array([25,60,5,10])
color=['green','yellow','pink','purple']
labe = ["AIML","Python","Pandas","Numpy"]
plt.pie(a,labels = labe,colors=color)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
print(iris)
sns.scatterplot(x="sepal_length",y="petal_length",data=iris,label='sepalvspetal')
plt.title("Scatter plot of total sepal vs petal")
plt.xlabel("sepal_length (cm)")
plt.ylabel("petal_length (cm)")
plt.legend(loc='best')
plt.show()



import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
#print(iris)
sns.barplot(x="day",y="total_bill",data=tips,label='dayvstoatl')
plt.title("Bar plot of totalbill vs day")
plt.xlabel(day (cm)")
plt.ylabel("total bill (cm)")
plt.legend(loc='best')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
#print(iris)
sns.boxplot(x="day",y="total_bill",data=tips)
plt.title("Box plot of totalbill vs day")
plt.xlabel("day")
plt.ylabel("total bill")
plt.legend(loc='best')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
#print(iris)
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("violin plot of totalbill vs day")
plt.xlabel("day")
plt.ylabel("total bill")
plt.legend(loc='best')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
a=pd.read_csv("/content/drive/MyDrive/dataset/grades_withnulls.csv")
#print(a)
b=sns.lineplot(x='SEM1',y='SEM2',data=a)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
cor_mat=iris.corr()
sns.heatmap(cor_mat,annot=True,cmap="hot")
plt.title("correlation matric heatmap of iris dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
#print(iris)
sns.jointplot(x="day",y="total_bill",data=tips)
plt.title("joint plot of totalbill vs day")
plt.xlabel("day")
plt.ylabel("total bill")
plt.legend(loc='best')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
#print(iris)
sns.countplot(x="day",data=tips)
plt.title("countplot of totalbill vs day")
plt.xlabel("day")
plt.ylabel("count")
plt.legend(loc='best')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
#print(tips)
sns.lmplot(x="tip",y="total_bill",data=tips)
plt.title("lm plot of totalbill vs day")
plt.xlabel("tip")
plt.ylabel("total bill")
plt.legend(loc='best')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
t=sns.load_dataset("titanic")
#print(iris)
g=sns.FacetGrid(t,col='class')
g.map(sns.histplot,"age")
plt.subplots_adjust(top=0.8)
g.fig.suptitle("Age distribution by passenger class")
plt.show()