# -*- coding: utf-8 -*-
"""NUMPY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vhHe3yyfwiOGWNxEBRBJyk1dFNYu4Peg
"""

import numpy as np
#array creation
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)
z=np.zeros((3,2),dtype=float)
print(z)
o=np.ones((3,3),dtype=int)
print(o)
a=np.arange(10)
print(a)
#array manipulation
reshape=arr.reshape(5,1)
print(reshape)
slice=arr[1:4]
print(slice)
transpose=arr.T
print(transpose)
a=np.array([1,2,3,4,5,6,7,8])
s=np.split(a,4)
print(s)

#matrix multiplicatin
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

import numpy as np
data=np.loadtxt("/content/drive/MyDrive/dataset (1)/data.txt",dtype=int)
d=np.savetxt("/content/date.txt",data)
print(d)
print(data)

a=np.arange(0,100,5)
print(a)
d=np.savetxt("/content/dat.txt",a)

import numpy as np
a=np.random.rand()
print(a)
b=np.random.randint(0,4)
print(b)
arr=np.array([[1,2],[3,4]])
print(type(arr))
print(arr.ndim)
print(arr.shape)



a=np.linspace(0.8,2,5)
print(a)

a=np.arange(24).reshape(1,6,4)
print(a)

a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(a*b)
print(a@b)
print(np.dot(a,b))

from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

c=np.random.random((2,12))
a=np.ceil(np.random.random((2,12)))
print(c)
print(a)

a=np.array([[1,2,3],[5,4,6]])
print(a)
print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))

b=np.array([[1,2],[3,4]])
a=np.array([[2,3,5,6]])
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))

a=np.array([[1,2,3,4,5,6]])
a.resize(3,2)
print(a)
print(a.shape)

a=np.array([[1,2,3,4,5,6]])
a.resize(2,3)
b=np.array([[7,8,9,10,11,12]])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

"""number of rows become number of groups,
coloumns become rows,
group become coulumn
"""

import numpy as np
a=np.eye(4)
print(a)
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)
x=[1,2,3]
a3=np.asarray(x)
print(type(a3))
print(a)

x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))#cfor cross product we have to change the order of the elements rows to column and then try it agian

a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])
print(np.rint(a))
b=np.array([10,20,30,40,50])
c=np.array([1,2,8,9,10])
np.true_divide(b,c)

a=np.array([1,2,3,1,2,3])
np.unique(a)
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[7,8,9],[3,5,2]])
np.union1d(b,c)
np.intersect1d(b,c)
np.setdiff1d(b,c)

a=8
b=6
c=np.hypot(a,b)
#print(c)
x=np.sin(0)
print(x)

a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)
d=np.mod(a,b)
print(d)
e=np.divide(a,b)
print(e)
f=np.multiply(a,b)
print(f)
g=np.matmul(a,b)
print(g)

from numpy import random
x=random.normal(size=(2,3))#gauseon distribution
print(x)
y=random.normal(loc=1,scale=2,size=(2,3))#loc=mean value scale=standard deviation
print(y)

x=random.binomial(n=12,p=0.5,size=10)#n=number of trail p=probability
print(x)
y=random.poisson(lam=2,size=10)#poisson distribution
print(y)
c=random.choice([1,4,3,5,6,8])
print(c)
d=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(d)